{% set name = "pytask-r" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_r-{{ version }}.tar.gz
  sha256: 9ba225931038050f9ba89376c60844f036b1782b05ee4fd6fda8d1343902cdd6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - toml
  run:
    - pytask >=0.1.0
    - python >=3.6

test:
  imports:
    - pytask_r
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-r
  summary: Run R scripts with pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-r
  doc_url: https://github.com/pytask-dev/pytask-r

extra:
  recipe-maintainers:
    - tobiasraabe
