{% set name = "pytask-r" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_r-{{ version }}.tar.gz
  sha256: 5a663db9e8ac27363ca85214ef4c7a7069071aa5fcd1fb2c357fe188c1a13809

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - pluggy
    - pybaum >=0.1.1
    - pytask >=0.3
    - python >=3.7

test:
  imports:
    - pytask_r
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-r
  summary: Run R scripts with pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-r
  doc_url: https://github.com/pytask-dev/pytask-r

extra:
  recipe-maintainers:
    - tobiasraabe
