{% set name = "pytask-r" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask-r-{{ version }}.tar.gz
  sha256: 8ab3dd5108749a421edb96de519f1fdd3a28aa4d2270a2a1ac4922e014d4132b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pytask >=0.0.9
    - python >=3.6

test:
  imports:
    - pytask_r
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-r
  summary: Run R scripts with pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-r
  doc_url: https://github.com/pytask-dev/pytask-r

extra:
  recipe-maintainers:
    - tobiasraabe
