{% set name = "pytask-r" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_r-{{ version }}.tar.gz
  sha256: b4e98c8af983796dc141e532731b279b400394d4a1e194f3b19da9f262856ed8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - pytask >=0.1.7
    - python >=3.7

test:
  imports:
    - pytask_r
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-r
  summary: Run R scripts with pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-r
  doc_url: https://github.com/pytask-dev/pytask-r

extra:
  recipe-maintainers:
    - tobiasraabe
