{% set name = "pytask-r" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_r-{{ version }}.tar.gz
  sha256: 0314f08c68355d0e1f8fcf38dc405566bb775d31dfa2e80313738b71b33fc9bd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - pytask >=0.1.7
    - python >=3.7

test:
  imports:
    - pytask_r
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-r
  summary: Run R scripts with pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-r
  doc_url: https://github.com/pytask-dev/pytask-r

extra:
  recipe-maintainers:
    - tobiasraabe
